=begin
#DockGenius API

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0
Contact: hi@dockgenius.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require "uri"

module DockGeniusApiRubyClient
  class MarinaApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Count instances of the model matched by where from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @return [InlineResponse200]
    def marina_count(opts = {})
      data, _status_code, _headers = marina_count_with_http_info(opts)
      return data
    end

    # Count instances of the model matched by where from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @return [Array<(InlineResponse200, Fixnum, Hash)>] InlineResponse200 data, response status code and response headers
    def marina_count_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_count ..."
      end
      # resource path
      local_var_path = "/Marinas/count".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'where'] = opts[:'where'] if !opts[:'where'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse200')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_count\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create a new instance of the model and persist it into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Marina]
    def marina_create(opts = {})
      data, _status_code, _headers = marina_create_with_http_info(opts)
      return data
    end

    # Create a new instance of the model and persist it into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_create_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_create ..."
      end
      # resource path
      local_var_path = "/Marinas".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create a change stream.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :options 
    # @return [File]
    def marina_create_change_stream_get_marinas_change_stream(opts = {})
      data, _status_code, _headers = marina_create_change_stream_get_marinas_change_stream_with_http_info(opts)
      return data
    end

    # Create a change stream.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :options 
    # @return [Array<(File, Fixnum, Hash)>] File data, response status code and response headers
    def marina_create_change_stream_get_marinas_change_stream_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_create_change_stream_get_marinas_change_stream ..."
      end
      # resource path
      local_var_path = "/Marinas/change-stream".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'options'] = opts[:'options'] if !opts[:'options'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'File')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_create_change_stream_get_marinas_change_stream\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create a change stream.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :options 
    # @return [File]
    def marina_create_change_stream_post_marinas_change_stream(opts = {})
      data, _status_code, _headers = marina_create_change_stream_post_marinas_change_stream_with_http_info(opts)
      return data
    end

    # Create a change stream.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :options 
    # @return [Array<(File, Fixnum, Hash)>] File data, response status code and response headers
    def marina_create_change_stream_post_marinas_change_stream_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_create_change_stream_post_marinas_change_stream ..."
      end
      # resource path
      local_var_path = "/Marinas/change-stream".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}
      form_params["options"] = opts[:'options'] if !opts[:'options'].nil?

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'File')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_create_change_stream_post_marinas_change_stream\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete a model instance by {{id}} from the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def marina_delete_by_id(id, opts = {})
      data, _status_code, _headers = marina_delete_by_id_with_http_info(id, opts)
      return data
    end

    # Delete a model instance by {{id}} from the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Fixnum, Hash)>] Object data, response status code and response headers
    def marina_delete_by_id_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_delete_by_id ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_delete_by_id" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Object')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_delete_by_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Check whether a model instance exists in the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse2002]
    def marina_exists_get_marinasid_exists(id, opts = {})
      data, _status_code, _headers = marina_exists_get_marinasid_exists_with_http_info(id, opts)
      return data
    end

    # Check whether a model instance exists in the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse2002, Fixnum, Hash)>] InlineResponse2002 data, response status code and response headers
    def marina_exists_get_marinasid_exists_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_exists_get_marinasid_exists ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_exists_get_marinasid_exists" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/exists".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2002')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_exists_get_marinasid_exists\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Check whether a model instance exists in the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse2002]
    def marina_exists_head_marinasid(id, opts = {})
      data, _status_code, _headers = marina_exists_head_marinasid_with_http_info(id, opts)
      return data
    end

    # Check whether a model instance exists in the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse2002, Fixnum, Hash)>] InlineResponse2002 data, response status code and response headers
    def marina_exists_head_marinasid_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_exists_head_marinasid ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_exists_head_marinasid" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:HEAD, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2002')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_exists_head_marinasid\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Find all instances of the model matched by filter from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter Filter defining fields, where, include, order, offset, and limit
    # @return [Array<Marina>]
    def marina_find(opts = {})
      data, _status_code, _headers = marina_find_with_http_info(opts)
      return data
    end

    # Find all instances of the model matched by filter from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter Filter defining fields, where, include, order, offset, and limit
    # @return [Array<(Array<Marina>, Fixnum, Hash)>] Array<Marina> data, response status code and response headers
    def marina_find_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_find ..."
      end
      # resource path
      local_var_path = "/Marinas".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'filter'] = opts[:'filter'] if !opts[:'filter'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Marina>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_find\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Find a model instance by {{id}} from the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter Filter defining fields and include
    # @return [Marina]
    def marina_find_by_id(id, opts = {})
      data, _status_code, _headers = marina_find_by_id_with_http_info(id, opts)
      return data
    end

    # Find a model instance by {{id}} from the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter Filter defining fields and include
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_find_by_id_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_find_by_id ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_find_by_id" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}
      query_params[:'filter'] = opts[:'filter'] if !opts[:'filter'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_find_by_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Find first instance of the model matched by filter from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter Filter defining fields, where, include, order, offset, and limit
    # @return [Marina]
    def marina_find_one(opts = {})
      data, _status_code, _headers = marina_find_one_with_http_info(opts)
      return data
    end

    # Find first instance of the model matched by filter from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter Filter defining fields, where, include, order, offset, and limit
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_find_one_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_find_one ..."
      end
      # resource path
      local_var_path = "/Marinas/findOne".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'filter'] = opts[:'filter'] if !opts[:'filter'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_find_one\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Counts docks of Marina.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @return [InlineResponse200]
    def marina_prototype_count_docks(id, opts = {})
      data, _status_code, _headers = marina_prototype_count_docks_with_http_info(id, opts)
      return data
    end

    # Counts docks of Marina.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @return [Array<(InlineResponse200, Fixnum, Hash)>] InlineResponse200 data, response status code and response headers
    def marina_prototype_count_docks_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_count_docks ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_count_docks" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/docks/count".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}
      query_params[:'where'] = opts[:'where'] if !opts[:'where'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse200')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_count_docks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Creates a new instance in address of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Address] :data 
    # @return [Address]
    def marina_prototype_create_address(id, opts = {})
      data, _status_code, _headers = marina_prototype_create_address_with_http_info(id, opts)
      return data
    end

    # Creates a new instance in address of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Address] :data 
    # @return [Array<(Address, Fixnum, Hash)>] Address data, response status code and response headers
    def marina_prototype_create_address_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_create_address ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_create_address" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/address".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Address')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_create_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Creates a new instance in docks of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Dock] :data 
    # @return [Dock]
    def marina_prototype_create_docks(id, opts = {})
      data, _status_code, _headers = marina_prototype_create_docks_with_http_info(id, opts)
      return data
    end

    # Creates a new instance in docks of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Dock] :data 
    # @return [Array<(Dock, Fixnum, Hash)>] Dock data, response status code and response headers
    def marina_prototype_create_docks_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_create_docks ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_create_docks" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/docks".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Dock')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_create_docks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Creates a new instance in listingAgent of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [ListingAgent] :data 
    # @return [ListingAgent]
    def marina_prototype_create_listing_agent(id, opts = {})
      data, _status_code, _headers = marina_prototype_create_listing_agent_with_http_info(id, opts)
      return data
    end

    # Creates a new instance in listingAgent of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [ListingAgent] :data 
    # @return [Array<(ListingAgent, Fixnum, Hash)>] ListingAgent data, response status code and response headers
    def marina_prototype_create_listing_agent_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_create_listing_agent ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_create_listing_agent" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/listingAgent".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'ListingAgent')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_create_listing_agent\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Deletes all docks of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def marina_prototype_delete_docks(id, opts = {})
      marina_prototype_delete_docks_with_http_info(id, opts)
      return nil
    end

    # Deletes all docks of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def marina_prototype_delete_docks_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_delete_docks ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_delete_docks" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/docks".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_delete_docks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Deletes address of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def marina_prototype_destroy_address(id, opts = {})
      marina_prototype_destroy_address_with_http_info(id, opts)
      return nil
    end

    # Deletes address of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def marina_prototype_destroy_address_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_destroy_address ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_destroy_address" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/address".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_destroy_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete a related item by id for docks.
    # 
    # @param fk Foreign key for docks
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def marina_prototype_destroy_by_id_docks(fk, id, opts = {})
      marina_prototype_destroy_by_id_docks_with_http_info(fk, id, opts)
      return nil
    end

    # Delete a related item by id for docks.
    # 
    # @param fk Foreign key for docks
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def marina_prototype_destroy_by_id_docks_with_http_info(fk, id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_destroy_by_id_docks ..."
      end
      # verify the required parameter 'fk' is set
      fail ArgumentError, "Missing the required parameter 'fk' when calling MarinaApi.marina_prototype_destroy_by_id_docks" if fk.nil?
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_destroy_by_id_docks" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/docks/{fk}".sub('{format}','json').sub('{' + 'fk' + '}', fk.to_s).sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_destroy_by_id_docks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Deletes listingAgent of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def marina_prototype_destroy_listing_agent(id, opts = {})
      marina_prototype_destroy_listing_agent_with_http_info(id, opts)
      return nil
    end

    # Deletes listingAgent of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def marina_prototype_destroy_listing_agent_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_destroy_listing_agent ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_destroy_listing_agent" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/listingAgent".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_destroy_listing_agent\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Find a related item by id for docks.
    # 
    # @param fk Foreign key for docks
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [Dock]
    def marina_prototype_find_by_id_docks(fk, id, opts = {})
      data, _status_code, _headers = marina_prototype_find_by_id_docks_with_http_info(fk, id, opts)
      return data
    end

    # Find a related item by id for docks.
    # 
    # @param fk Foreign key for docks
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @return [Array<(Dock, Fixnum, Hash)>] Dock data, response status code and response headers
    def marina_prototype_find_by_id_docks_with_http_info(fk, id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_find_by_id_docks ..."
      end
      # verify the required parameter 'fk' is set
      fail ArgumentError, "Missing the required parameter 'fk' when calling MarinaApi.marina_prototype_find_by_id_docks" if fk.nil?
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_find_by_id_docks" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/docks/{fk}".sub('{format}','json').sub('{' + 'fk' + '}', fk.to_s).sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Dock')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_find_by_id_docks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Fetches hasOne relation address.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [BOOLEAN] :refresh 
    # @return [Address]
    def marina_prototype_get_address(id, opts = {})
      data, _status_code, _headers = marina_prototype_get_address_with_http_info(id, opts)
      return data
    end

    # Fetches hasOne relation address.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [BOOLEAN] :refresh 
    # @return [Array<(Address, Fixnum, Hash)>] Address data, response status code and response headers
    def marina_prototype_get_address_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_get_address ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_get_address" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/address".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}
      query_params[:'refresh'] = opts[:'refresh'] if !opts[:'refresh'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Address')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_get_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Queries docks of Marina.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter 
    # @return [Array<Dock>]
    def marina_prototype_get_docks(id, opts = {})
      data, _status_code, _headers = marina_prototype_get_docks_with_http_info(id, opts)
      return data
    end

    # Queries docks of Marina.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :filter 
    # @return [Array<(Array<Dock>, Fixnum, Hash)>] Array<Dock> data, response status code and response headers
    def marina_prototype_get_docks_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_get_docks ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_get_docks" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/docks".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}
      query_params[:'filter'] = opts[:'filter'] if !opts[:'filter'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Dock>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_get_docks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Fetches hasOne relation listingAgent.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [BOOLEAN] :refresh 
    # @return [ListingAgent]
    def marina_prototype_get_listing_agent(id, opts = {})
      data, _status_code, _headers = marina_prototype_get_listing_agent_with_http_info(id, opts)
      return data
    end

    # Fetches hasOne relation listingAgent.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [BOOLEAN] :refresh 
    # @return [Array<(ListingAgent, Fixnum, Hash)>] ListingAgent data, response status code and response headers
    def marina_prototype_get_listing_agent_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_get_listing_agent ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_get_listing_agent" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/listingAgent".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}
      query_params[:'refresh'] = opts[:'refresh'] if !opts[:'refresh'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'ListingAgent')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_get_listing_agent\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update address of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Address] :data 
    # @return [Address]
    def marina_prototype_update_address(id, opts = {})
      data, _status_code, _headers = marina_prototype_update_address_with_http_info(id, opts)
      return data
    end

    # Update address of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Address] :data 
    # @return [Array<(Address, Fixnum, Hash)>] Address data, response status code and response headers
    def marina_prototype_update_address_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_update_address ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_update_address" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/address".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Address')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_update_address\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Patch attributes for a model instance and persist it into the data source.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [Marina]
    def marina_prototype_update_attributes_patch_marinasid(id, opts = {})
      data, _status_code, _headers = marina_prototype_update_attributes_patch_marinasid_with_http_info(id, opts)
      return data
    end

    # Patch attributes for a model instance and persist it into the data source.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_prototype_update_attributes_patch_marinasid_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_update_attributes_patch_marinasid ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_update_attributes_patch_marinasid" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_update_attributes_patch_marinasid\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Patch attributes for a model instance and persist it into the data source.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [Marina]
    def marina_prototype_update_attributes_put_marinasid(id, opts = {})
      data, _status_code, _headers = marina_prototype_update_attributes_put_marinasid_with_http_info(id, opts)
      return data
    end

    # Patch attributes for a model instance and persist it into the data source.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_prototype_update_attributes_put_marinasid_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_update_attributes_put_marinasid ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_update_attributes_put_marinasid" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_update_attributes_put_marinasid\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update a related item by id for docks.
    # 
    # @param fk Foreign key for docks
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Dock] :data 
    # @return [Dock]
    def marina_prototype_update_by_id_docks(fk, id, opts = {})
      data, _status_code, _headers = marina_prototype_update_by_id_docks_with_http_info(fk, id, opts)
      return data
    end

    # Update a related item by id for docks.
    # 
    # @param fk Foreign key for docks
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [Dock] :data 
    # @return [Array<(Dock, Fixnum, Hash)>] Dock data, response status code and response headers
    def marina_prototype_update_by_id_docks_with_http_info(fk, id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_update_by_id_docks ..."
      end
      # verify the required parameter 'fk' is set
      fail ArgumentError, "Missing the required parameter 'fk' when calling MarinaApi.marina_prototype_update_by_id_docks" if fk.nil?
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_update_by_id_docks" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/docks/{fk}".sub('{format}','json').sub('{' + 'fk' + '}', fk.to_s).sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Dock')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_update_by_id_docks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update listingAgent of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [ListingAgent] :data 
    # @return [ListingAgent]
    def marina_prototype_update_listing_agent(id, opts = {})
      data, _status_code, _headers = marina_prototype_update_listing_agent_with_http_info(id, opts)
      return data
    end

    # Update listingAgent of this model.
    # 
    # @param id PersistedModel id
    # @param [Hash] opts the optional parameters
    # @option opts [ListingAgent] :data 
    # @return [Array<(ListingAgent, Fixnum, Hash)>] ListingAgent data, response status code and response headers
    def marina_prototype_update_listing_agent_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_prototype_update_listing_agent ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_prototype_update_listing_agent" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/listingAgent".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'ListingAgent')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_prototype_update_listing_agent\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Replace attributes for a model instance and persist it into the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Marina]
    def marina_replace_by_id(id, opts = {})
      data, _status_code, _headers = marina_replace_by_id_with_http_info(id, opts)
      return data
    end

    # Replace attributes for a model instance and persist it into the data source.
    # 
    # @param id Model id
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_replace_by_id_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_replace_by_id ..."
      end
      # verify the required parameter 'id' is set
      fail ArgumentError, "Missing the required parameter 'id' when calling MarinaApi.marina_replace_by_id" if id.nil?
      # resource path
      local_var_path = "/Marinas/{id}/replace".sub('{format}','json').sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_replace_by_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Replace an existing model instance or insert a new one into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Marina]
    def marina_replace_or_create(opts = {})
      data, _status_code, _headers = marina_replace_or_create_with_http_info(opts)
      return data
    end

    # Replace an existing model instance or insert a new one into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_replace_or_create_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_replace_or_create ..."
      end
      # resource path
      local_var_path = "/Marinas/replaceOrCreate".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_replace_or_create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update instances of the model matched by {{where}} from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [InlineResponse2001]
    def marina_update_all(opts = {})
      data, _status_code, _headers = marina_update_all_with_http_info(opts)
      return data
    end

    # Update instances of the model matched by {{where}} from the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [Array<(InlineResponse2001, Fixnum, Hash)>] InlineResponse2001 data, response status code and response headers
    def marina_update_all_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_update_all ..."
      end
      # resource path
      local_var_path = "/Marinas/update".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'where'] = opts[:'where'] if !opts[:'where'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2001')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_update_all\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Patch an existing model instance or insert a new one into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Marina]
    def marina_upsert_patch_marinas(opts = {})
      data, _status_code, _headers = marina_upsert_patch_marinas_with_http_info(opts)
      return data
    end

    # Patch an existing model instance or insert a new one into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_upsert_patch_marinas_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_upsert_patch_marinas ..."
      end
      # resource path
      local_var_path = "/Marinas".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_upsert_patch_marinas\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Patch an existing model instance or insert a new one into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Marina]
    def marina_upsert_put_marinas(opts = {})
      data, _status_code, _headers = marina_upsert_put_marinas_with_http_info(opts)
      return data
    end

    # Patch an existing model instance or insert a new one into the data source.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Marina] :data Model instance data
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_upsert_put_marinas_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_upsert_put_marinas ..."
      end
      # resource path
      local_var_path = "/Marinas".sub('{format}','json')

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_upsert_put_marinas\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update an existing model instance or insert a new one into the data source based on the where criteria.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [Marina]
    def marina_upsert_with_where(opts = {})
      data, _status_code, _headers = marina_upsert_with_where_with_http_info(opts)
      return data
    end

    # Update an existing model instance or insert a new one into the data source based on the where criteria.
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :where Criteria to match model instances
    # @option opts [Marina] :data An object of model property name/value pairs
    # @return [Array<(Marina, Fixnum, Hash)>] Marina data, response status code and response headers
    def marina_upsert_with_where_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MarinaApi.marina_upsert_with_where ..."
      end
      # resource path
      local_var_path = "/Marinas/upsertWithWhere".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'where'] = opts[:'where'] if !opts[:'where'].nil?

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      local_header_accept = ['application/json', 'application/xml', 'text/xml', 'application/javascript', 'text/javascript']
      local_header_accept_result = @api_client.select_header_accept(local_header_accept) and header_params['Accept'] = local_header_accept_result

      # HTTP header 'Content-Type'
      local_header_content_type = ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/xml']
      header_params['Content-Type'] = @api_client.select_header_content_type(local_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'data'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Marina')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MarinaApi#marina_upsert_with_where\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
