=begin
#DockGenius API

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0
Contact: hi@dockgenius.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module DockGeniusApiRubyClient
  # This class describes a physical dock or slip.
  class Dock
    attr_accessor :id

    # The name given to the dock (usually by a marina with many docks).
    attr_accessor :common_name

    # The URL to the image that shows this dock
    attr_accessor :image_url

    # The coordinates of this dock. If a boundary GeoJSON is provided, this attribute may be overridden at creation or update
    attr_accessor :location

    # A GeoJSON fragment representing the boundary of the slip. If this attribute is provided at creation or update it overrides the location
    attr_accessor :boundary_geo_json

    # Indicates if it is a slip (true) or a dock (false)
    attr_accessor :is_slip

    # Indicates if it is listed for rent
    attr_accessor :for_rent

    # Indicates if it is listed for sale
    attr_accessor :for_sale

    # An URI that tries to link this record to a source
    attr_accessor :source

    attr_accessor :created

    attr_accessor :last_updated

    attr_accessor :marina_id

    attr_accessor :_listing_agent

    attr_accessor :_parameter_assignments


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'common_name' => :'commonName',
        :'image_url' => :'imageURL',
        :'location' => :'location',
        :'boundary_geo_json' => :'boundaryGeoJSON',
        :'is_slip' => :'isSlip',
        :'for_rent' => :'forRent',
        :'for_sale' => :'forSale',
        :'source' => :'source',
        :'created' => :'created',
        :'last_updated' => :'lastUpdated',
        :'marina_id' => :'marinaId',
        :'_listing_agent' => :'_listingAgent',
        :'_parameter_assignments' => :'_parameterAssignments'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'Float',
        :'common_name' => :'String',
        :'image_url' => :'String',
        :'location' => :'GeoPoint',
        :'boundary_geo_json' => :'String',
        :'is_slip' => :'BOOLEAN',
        :'for_rent' => :'BOOLEAN',
        :'for_sale' => :'BOOLEAN',
        :'source' => :'String',
        :'created' => :'Date',
        :'last_updated' => :'Date',
        :'marina_id' => :'Float',
        :'_listing_agent' => :'ListingAgent',
        :'_parameter_assignments' => :'Array<ParameterAssignment>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'commonName')
        self.common_name = attributes[:'commonName']
      else
        self.common_name = ""
      end

      if attributes.has_key?(:'imageURL')
        self.image_url = attributes[:'imageURL']
      else
        self.image_url = ""
      end

      if attributes.has_key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.has_key?(:'boundaryGeoJSON')
        self.boundary_geo_json = attributes[:'boundaryGeoJSON']
      else
        self.boundary_geo_json = ""
      end

      if attributes.has_key?(:'isSlip')
        self.is_slip = attributes[:'isSlip']
      else
        self.is_slip = false
      end

      if attributes.has_key?(:'forRent')
        self.for_rent = attributes[:'forRent']
      else
        self.for_rent = false
      end

      if attributes.has_key?(:'forSale')
        self.for_sale = attributes[:'forSale']
      else
        self.for_sale = false
      end

      if attributes.has_key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.has_key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.has_key?(:'lastUpdated')
        self.last_updated = attributes[:'lastUpdated']
      end

      if attributes.has_key?(:'marinaId')
        self.marina_id = attributes[:'marinaId']
      end

      if attributes.has_key?(:'_listingAgent')
        self._listing_agent = attributes[:'_listingAgent']
      end

      if attributes.has_key?(:'_parameterAssignments')
        if (value = attributes[:'_parameterAssignments']).is_a?(Array)
          self._parameter_assignments = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @common_name.nil?
      return false if @location.nil?
      return false if @is_slip.nil?
      return false if @for_rent.nil?
      return false if @for_sale.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          common_name == o.common_name &&
          image_url == o.image_url &&
          location == o.location &&
          boundary_geo_json == o.boundary_geo_json &&
          is_slip == o.is_slip &&
          for_rent == o.for_rent &&
          for_sale == o.for_sale &&
          source == o.source &&
          created == o.created &&
          last_updated == o.last_updated &&
          marina_id == o.marina_id &&
          _listing_agent == o._listing_agent &&
          _parameter_assignments == o._parameter_assignments
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, common_name, image_url, location, boundary_geo_json, is_slip, for_rent, for_sale, source, created, last_updated, marina_id, _listing_agent, _parameter_assignments].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DockGeniusApiRubyClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
